/*Copyright 2008 by Vladimir Polony, Stupy 24, Banska Bystrica, Slovakia

This file is part of OpenRep FREE homeopathic software.

    OpenRep FREE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenRep FREE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenRep FREE.  If not, see <http://www.gnu.org/licenses/>.*/

/* The dialog used to enter patients data
 *
 * Created on September 1, 2008, 1:04 PM
 */

package prescriber;

import java.awt.Font;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

public class PatientDialog extends javax.swing.JDialog {
    /** contains the entered patient, or null if CANCEL was pressed*/
    public Patient result = null;
    /** contains the instance of the PrescriberView */
    private PrescriberView main_editor;
    
    /** Creates new form PatientDialog */
    public PatientDialog(java.awt.Frame parent, boolean modal, PrescriberView pw) {
        super(parent, modal);
        this.main_editor = pw;
        initComponents();

        int size = main_editor.config.GetValue(Configuration.Key_PatientDialog_AdditionalInformationEdit);
        Font ft;
        if (size != -1) {
            ft = new Font(AdditionalInformationEdit.getFont().getName(), AdditionalInformationEdit.getFont().getStyle(), size);
            AdditionalInformationEdit.setFont(ft);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        NameEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SurnameEdit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddressEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TelephoneEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdditionalInformationEdit = new javax.swing.JTextArea();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        MaleRadio = new javax.swing.JRadioButton();
        FemaleRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        BirthEdit = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(prescriber.PrescriberApp.class).getContext().getResourceMap(PatientDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        NameEdit.setText(resourceMap.getString("NameEdit.text")); // NOI18N
        NameEdit.setName("NameEdit"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        SurnameEdit.setText(resourceMap.getString("SurnameEdit.text")); // NOI18N
        SurnameEdit.setName("SurnameEdit"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        AddressEdit.setText(resourceMap.getString("AddressEdit.text")); // NOI18N
        AddressEdit.setName("AddressEdit"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        TelephoneEdit.setText(resourceMap.getString("TelephoneEdit.text")); // NOI18N
        TelephoneEdit.setName("TelephoneEdit"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        EmailEdit.setText(resourceMap.getString("EmailEdit.text")); // NOI18N
        EmailEdit.setName("EmailEdit"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        AdditionalInformationEdit.setColumns(20);
        AdditionalInformationEdit.setFont(resourceMap.getFont("AdditionalInformationEdit.font")); // NOI18N
        AdditionalInformationEdit.setRows(5);
        AdditionalInformationEdit.setName("AdditionalInformationEdit"); // NOI18N
        AdditionalInformationEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdditionalInformationEditKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(AdditionalInformationEdit);

        OKButton.setText(resourceMap.getString("OKButton.text")); // NOI18N
        OKButton.setName("OKButton"); // NOI18N
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText(resourceMap.getString("CancelButton.text")); // NOI18N
        CancelButton.setName("CancelButton"); // NOI18N
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel8.setName("jLabel8"); // NOI18N

        MaleRadio.setSelected(true);
        MaleRadio.setText(resourceMap.getString("MaleRadio.text")); // NOI18N
        MaleRadio.setName("MaleRadio"); // NOI18N
        MaleRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MaleRadioItemStateChanged(evt);
            }
        });

        FemaleRadio.setText(resourceMap.getString("FemaleRadio.text")); // NOI18N
        FemaleRadio.setName("FemaleRadio"); // NOI18N
        FemaleRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FemaleRadioItemStateChanged(evt);
            }
        });

        jLabel9.setName("jLabel9"); // NOI18N

        BirthEdit.setName("BirthEdit"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setName("jLabel11"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jLabel1)
                            .add(jLabel3)
                            .add(jLabel10)
                            .add(jLabel4)
                            .add(jLabel6))
                        .add(4, 4, 4)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(TelephoneEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .add(18, 18, 18)
                                .add(jLabel5)
                                .add(31, 31, 31)
                                .add(EmailEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(NameEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(MaleRadio)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(FemaleRadio)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel11)
                                    .add(jLabel2)
                                    .add(jLabel12))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(136, 136, 136)
                                        .add(jLabel9))
                                    .add(SurnameEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .add(BirthEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .add(AddressEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel7))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(143, 143, 143)
                        .add(OKButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(128, 128, 128)
                        .add(CancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(NameEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(SurnameEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(BirthEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(MaleRadio)
                    .add(FemaleRadio)
                    .add(jLabel6)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(AddressEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(EmailEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(TelephoneEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(OKButton)
                    .add(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
   this.setVisible(false);
}//GEN-LAST:event_CancelButtonActionPerformed

private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
   if (NameEdit.getText().trim().equals("") || SurnameEdit.getText().trim().equals("")) {
       JOptionPane.showMessageDialog(rootPane, "Sie müssen mind. einen Namen und Vornamen für den Patienten angeben");
       return;
   }

   String temp = BirthEdit.getText().trim();
   String dob = "";
   if (!temp.equals("")) {
       String[] temps = temp.split("/");

       Calendar cal = Calendar.getInstance();

       int year, month, day;
       try {
           year = Integer.parseInt(temps[0]);
       } catch (Exception e) {
           year = -1;
       }

       try {
           month = Integer.parseInt(temps[1]);
       } catch (Exception e) {
           month = -1;
       }

       try {
           day = Integer.parseInt(temps[2]);
       } catch (Exception e) {
           day = -1;
       }       

       if (temps.length == 1) {
           if (year >= 150) dob = temps[0]+"/01/01";
           else
           dob = String.valueOf(cal.get(Calendar.YEAR) - year) +"/01/01";
       }
       else if (temps.length == 2) {
           if (year >= 150) {
               dob = temps[0] + "/" + month + "/01";
           }
           else {
               int mnth = (cal.get(Calendar.MONTH) + 1 - month);
               if (mnth <= 0) {
                   mnth = 12 + mnth;
                   year = cal.get(Calendar.YEAR) - year - 1;
               }
               else
               year = cal.get(Calendar.YEAR) - year;
               dob = String.valueOf(year) + "/" + (mnth) + "/01";
           }
           
       }
       else if (temps.length == 3) {
           dob = temps[0] + "/" + temps[1] + "/" + temps[2];
       }
       if ((temps.length == 3 && Utils.ConvertDateToAge(BirthEdit.getText()).equals("")) || temps.length > 3) {
          JOptionPane.showMessageDialog(rootPane, "Bitte geben Sie ein korrektes Datum an (jjj/mm/tt).");
          return;
       }
   }
   result = new Patient ();
   result.additional_information = AdditionalInformationEdit.getText();
   result.address = AddressEdit.getText().trim();
   result.comment = "";
   result.email = EmailEdit.getText().trim();
   result.name = NameEdit.getText().trim();
   result.surname = SurnameEdit.getText().trim();
   result.telephone = TelephoneEdit.getText().trim();
   result.sex = MaleRadio.isSelected();
   result.date_of_birth = dob;
   this.setVisible(false);
}//GEN-LAST:event_OKButtonActionPerformed

private void MaleRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MaleRadioItemStateChanged
    FemaleRadio.setSelected(!MaleRadio.isSelected());
}//GEN-LAST:event_MaleRadioItemStateChanged

private void FemaleRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FemaleRadioItemStateChanged
    MaleRadio.setSelected(!FemaleRadio.isSelected());
}//GEN-LAST:event_FemaleRadioItemStateChanged

private void AdditionalInformationEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdditionalInformationEditKeyPressed
    if (evt.isAltDown()) {
        if (evt.getKeyCode() == evt.VK_UP) {
            Utils.ChangeFont(AdditionalInformationEdit, 1);
            main_editor.config.SetValue(Configuration.Key_PatientDialog_AdditionalInformationEdit, AdditionalInformationEdit.getFont().getSize());
        }
        else
        if (evt.getKeyCode() == evt.VK_DOWN) {
            Utils.ChangeFont(AdditionalInformationEdit, -1);
            main_editor.config.SetValue(Configuration.Key_PatientDialog_AdditionalInformationEdit, AdditionalInformationEdit.getFont().getSize());
        }
    }
}//GEN-LAST:event_AdditionalInformationEditKeyPressed

/** Sets the edits according to the parameter
 * 
 * @param p
 */
  public void SetData (Patient p) {
      if (p == null) return;
      AdditionalInformationEdit.setText(p.additional_information);
      AddressEdit.setText(p.address);
      EmailEdit.setText(p.email);
      NameEdit.setText(p.name);
      SurnameEdit.setText(p.surname);
      TelephoneEdit.setText(p.telephone);
      BirthEdit.setText(p.date_of_birth);
      MaleRadio.setSelected(p.sex);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AdditionalInformationEdit;
    private javax.swing.JTextField AddressEdit;
    private javax.swing.JTextField BirthEdit;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField EmailEdit;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField NameEdit;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField SurnameEdit;
    private javax.swing.JTextField TelephoneEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
